# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule: 
    # * is a special character in YAML so you have to quote this string
    # - cron:  '*/15 * * * *'   # Runs every 15 mins
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Dump Github content
      env:
        EVENT_METADATA: ${{ toJSON(github) }}
      run: echo "$EVENT_METADATA"

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: actions/cache@v2.1.4
      id: gradle-cache
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    - uses: actions/cache@v2.1.4
      id: gradle-wrapper-cache
      with:
        path: |
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/*') }}
    - name: Build
      run: ./gradlew build
      
    - name: Print working directory
      run: |
        cd ./
        ls
        mkdir target
        for i in $(find . -name \*.jar); do cp "$i" ./target/; done
        ls target/
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Region to access CodeGuru 
        
    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      with:
        build_path: target # build artifact(s) directory
        s3_bucket: codeguru-reviewer-github-xxz-test-iad  # S3 Bucket with "codeguru-reviewer-*" prefix

    - name: Upload review result
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
